SeaDiscovery/config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  root 'static_pages#home'
    
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do 
    resources :orderitems
  end

  
  get '/home' => 'static_pages#home'
  
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  
 
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  get '/category/:title' =>  'static_pages#category'
  
  
  resources :items
  
  
  devise_for :users do
    resources :orders
  end
    
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/reduce/:id' => 'cart#reduce'
  get '/cart/increase/:id' => 'cart#increase'
  
  get '/checkout' => 'cart#createOrder'
   get '/checkout' => 'orders#create'
 
  post '/search' => 'items#search'
  
  get '/aboutSend/:id' => 'static_pages#aboutSend'
  
  
end

SeaDiscovery/app/views/layouts/_categories.html.erb
 <% @categories.each do |category| %>
       <div class="itemhols">
           <p><%= category.title %></p>
           <%= link_to (image_tag category.image, :class=>"itemholsIm"), category %>
           <p><%= category.description %></p>
            
           <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>
           
         </div>
    
    <% end %>

SeaDiscovery/app/views/layouts/_footer.html.erb
<footer class="foot">
  <p>Author: Blerta(Eleni) Tzafai <br>
  <a href="x19224320@student.ncirl.ie">x19224320@student.ncirl.ie</a></p>
    <p>For any queries relating to orders, deliveries, returns or issues with the website, contact our Customer Service.
     And by By Clicking the below Link you will find more
     
      <h3> <a href="/help/">CONTACT US FOR SUPPORT</h3></a>  
     
</p>
</footer>

SeaDiscovery/app/views/layouts/_header.html.erb
   <header class="headSec">
     
      <h1>SeaDiscovery</h1>
      
      <ul>
        <li><%= link_to "Home",  "/" %></li>
        <li><%= link_to "Products", items_path %></li>
        <li><%= link_to "About", about_path  %></li>
        <li><%= link_to "Help", help_path %></li>
 
          
         <% if user_signed_in? %>
        <li><%= link_to "View Cart", cart_path %></li>
        <li><%= link_to "View Orders", orders_path  %></li>
                 <!--
                 <li><a href="#">Hi <%= current_user.email %></a></li>
                 
                 -->
                 <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                 <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
                 <li><%= link_to 'Register', new_user_registration_path %></li> 
                 <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>

         
        <% if session[:login] == 1 %>    
          <li><%= link_to "Admin Log Out",   logout_path %></li>
        <% else %>
          <li><%= link_to "Admin Log In",   login_path %></li>
        <% end %>
        
        
      </ul>
      
   
   </header>

SeaDiscovery/app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

SeaDiscovery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeaDiscovery <%= yield (:title) %></title>
    
    <%= csrf_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

 
  <body>
   
    <%= render 'layouts/header' %>

    <div class="container">
      <div id="content">
      
        <%= yield %>
      </div>
      <div id="first-column">
         
        
          <div class="searchbox">
            <h2 class="BoxHeaders">Search For your Products!! ...</h2>
            
            <%=render 'layouts/search'%>


          </div>
      </div>
   </div>
 
  <%= render 'layouts/footer' %>

  </body>
</html>