SeaDiscovery/config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  root 'static_pages#home'
    
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do 
    resources :orderitems
  end

  
  get '/home' => 'static_pages#home'
  
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  
 
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  get '/category/:title' =>  'static_pages#category'
  
  
  resources :items
  
  
  devise_for :users do
    resources :orders
  end
    
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/reduce/:id' => 'cart#reduce'
  get '/cart/increase/:id' => 'cart#increase'
  
  get '/checkout' => 'cart#createOrder'
   get '/checkout' => 'orders#create'
 
  post '/search' => 'items#search'
  
  get '/aboutSend/:id' => 'static_pages#aboutSend'
  
  
end

SeaDiscovery/app/models/item.rb
class Item < ApplicationRecord
    has_many :orders
    has_many :users
end

SeaDiscovery/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
     st = "%#{params[:q]}%"
     @items = Item.where("title like ?", st)
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
end

SeaDiscovery/app/helpers/items_helper.rb
module ItemsHelper
end

SeaDiscovery/app/views/items/_form.html.erb
<div class="mainCont">
  
<%= form_for(@item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_titl, :type =>"text"%>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_description, :type =>"text" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price, :type =>"text" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :item_image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category, :type =>"text" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

SeaDiscovery/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

SeaDiscovery/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Product Items</h1>
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
      
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
       <p><%= item.description %>
       <br>Price <%= number_to_currency(item.price, :unit => "€") %></br>
       <br>
        Category: <%= item.category %>
        </br>
       </p>
       
       <p>
        <!--
         <% if user_signed_in? %> 
          <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
         <% end %>
           -->
           <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
           
           
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <% if session[:login] == 1 %>    
           <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
           <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
        <% end %>
       </p>
        
      </div>
    <% end %>
      
</div>

<br>

 
 <% if session[:login] == 1 %>  
  <%= link_to 'New Item', new_item_path, :class =>"button", :role=>"button" %>
<%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button" %>
<%end %>

SeaDiscovery/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

SeaDiscovery/app/views/items/search.html.erb
<h2>You Searched For: <%= @search_term %></h2>
<% if @items.length == 0 %>
<br />
<h2>No products were found to match your search</h2>
<% end %>
<table class="catalog">
 <% @items.each do |item| %>
 <tr>
 <td>
 <div class="image">
 <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
 </div>
 <div class="title">
 <%= link_to item.title, item %>
 </div>
 <div class="description">
 <%= item.description %>
 </div>
 <div class="price">
 <%= number_to_currency(item.price, :unit => "€") %>
 </div>
 <div class="links">
  
 <% if session[:login] == 1 %> 
    
 <%= link_to 'Edit', edit_item_path(item) %>
 <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
 <%else%>

 <a href="/cart/<%= item.id %>">Add to Cart</a>
 <%end%>
 </div>
 </td>
 </tr>
 <% end %>
</table>

SeaDiscovery/app/views/items/show.html.erb
<div id="itemsContainer">
   <h1><%= @item.title %></h1>
   <%= image_tag @item.image_url, :class => 'welcomIm'  %>
       <h2><%= @item.description %></h1>
   
    <div class="itemhols">
       <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
       <br>
        Category: <%= @item.category %>
        <br>
        </p>
       
       <p>
         <a href="/cart/<%= @item.id %>" class="button">Add To Cart</a>
         <%= link_to 'Back',  items_path, :class => "button", :role => "button" %>
        <!-- <%= link_to 'Edit',  edit_item_path(@item), :class => "button", :role => "button" %> -->
          
          
           <a href="/cart/clear" class="button">Clear Cart</a>
         
       </p>
        
      </div>
   
   
  </div>